server:
  port: 9191

#eureka properties
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: EMS-DB
          predicates:
            - Path=/employees/**
          uri: localhost:8081
        - id: EMS-PORTAL
          predicates:
            - Path=/home
          uri: localhost:8080